### Multi Variable Linear Regression

In [2]:
import tensorflow as tf

x_data = [[73, 80, 75],
          [93, 88, 93],
          [89, 91, 90],
          [96, 98, 100],
          [73, 66, 70],
          [53, 46, 55]]
y_data = [[152], [185], [180], [196], [142], [101]]

# Placeholders
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Cost function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Init session
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={X: x_data, Y: y_data})
    if step % 100 == 0:
        print(step, 'Cost: ', cost_val)
        print('Priediction')
        print(hy_val)

0 Cost:  44046.47
Priediction
[[-44.25118 ]
 [-53.46344 ]
 [-52.57093 ]
 [-57.75147 ]
 [-40.26363 ]
 [-30.150295]]
100 Cost:  1.7522779
Priediction
[[152.72571]
 [183.37834]
 [180.74614]
 [196.33289]
 [140.40294]
 [103.03448]]
200 Cost:  1.7411121
Priediction
[[152.71402]
 [183.3855 ]
 [180.7426 ]
 [196.32523]
 [140.41676]
 [103.04117]]
300 Cost:  1.7302923
Priediction
[[152.70274]
 [183.39243]
 [180.7392 ]
 [196.31769]
 [140.43028]
 [103.0475 ]]
400 Cost:  1.7197732
Priediction
[[152.69183]
 [183.39917]
 [180.73596]
 [196.31024]
 [140.44353]
 [103.0535 ]]
500 Cost:  1.709525
Priediction
[[152.68129]
 [183.40573]
 [180.73285]
 [196.30295]
 [140.45651]
 [103.05915]]
600 Cost:  1.6995497
Priediction
[[152.67111]
 [183.41212]
 [180.7299 ]
 [196.29576]
 [140.46924]
 [103.06448]]
700 Cost:  1.6898355
Priediction
[[152.66129]
 [183.41833]
 [180.72708]
 [196.28868]
 [140.4817 ]
 [103.0695 ]]
800 Cost:  1.680366
Priediction
[[152.6518  ]
 [183.42438 ]
 [180.7244  ]
 [196.28172 ]
 [140.49394 ]


In [3]:
# Test
sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]})

array([[152.57248],
       [182.59387]], dtype=float32)